Fix error on Linux machine
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.solr.environment.PARTIAL_SEARCH_ENABLED contains false, which is an invalid type, it should be a string, number, or a null